version: "3.9"
   
services:
  postgres:
    image: postgres:9.4
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
  flask:
    build: ./flask
    ports:
      - "5000:5000"
    depends_on:
      - "postgres"
  client:
    build: ./client/rolesui
    ports:
        - "8080:8080"
    volumes:
        - ./client/rolesui:/usr/src/app
    depends_on:
        - "flask"
